ANDROID_AUTOMATION_NAME: UIAutomator2
ANDROID_PLATFORM_NAME: Android
ANDROID_PLATFORM_VERSION: "%{ANDROID_PLATFORM_VERSION=13}"
ANDROID_APP_PACKAGE: sg.gov.ica.mobile.app
ANDROID_DEVICE_NAME: RFCN90WD11Y
ANDROID_EMULATOR_NAME: emulator-5554